version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - /code/node_modules
      - ./frontend:/code
    restart: unless-stopped
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  reverse-proxy:
    depends_on:
      - frontend
      - strapi
    image: caddy:latest
    ports:
      - 3000:3000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
